name: Quality & Security Checks

on:
  push:
    branches: [futureprep]
  pull_request:
    branches: [futureprep]

jobs:
  quality:
    name: Does it build?
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Build Next.js
        run: npm run build

  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: npm audit (fail on ≥moderate)
        run: npm audit --audit-level=moderate

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    needs: [quality, audit]
    permissions:
      actions: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3
